### ISSUE TITLE
`v0.1.2` breaks toml deserialization

### ISSUE THREAD

**Issue by erwanor** [cjriches/serde_unit_struct#2] opened 2023-11-15 12:57 UTC
Hi @cjriches, thanks for your work in this crate. I'm reaching out because the latest release of `serde_unit_struct` is breaking our build and without making demands from your time, I wonder if you could consider yanking the release and bumping a major version so that we can opt-out. I am happy to prepare the release of `0.2.0` for you, though you will have to go on `crates.io` to yank the previous `0.1.2` release.  

The problem is subtle and arise when combining different serde serialization methods. We have a struct mapping to a toml config. Using `toml@0.7` and `serde_unit_struct@0.1.1` we are able to deserialize into the struct without issues. But running `cargo update serde_unit_struct` makes the untagged union unrecognizable to the toml serializer, which I think is related to the fact that it quietly expects an owned type.

**Comment by cjriches** [comment] 2023-11-15 13:27
Apologies for the breakage. I've yanked `v0.1.2`, but would like to understand the breakage better before I make any new releases. Can you provide a minimal reproducible example?

**Comment by erwanor** [comment] 2023-11-15 14:01
No worries, and thanks a lot for looking into this. Here's a somewhat minimal repro: https://github.com/erwanor/unit_struct_repro

If you run `cargo run` this will fail, but you can cd into the vendored `serde_unit_struct` import and rollback a commit and it will work.

**Comment by FrozenDroid** [comment] 2023-11-16 19:33
@erwanor 
> which I think is related to the fact that it quietly expects an owned type.  

I agree. I'm trying to find a way now to make it work for both borrowed and owned strings.

**Comment by cjriches** [comment] 2023-11-16 22:22
Thanks to both of you for the help, and apologies that I've been busy with my day job. @FrozenDroid I agree with your proposal to use a `Visitor`; it's egg on my face that I never read https://serde.rs/impl-deserialize.html that makes it quite clear this is the intended approach.

**Comment by cjriches** [comment] 2023-11-17 00:51
@erwanor @FrozenDroid I've pushed a fix to main. It would be great if one or both of you could try it out before I publish to crates.io.

**Comment by cjriches** [comment] 2023-11-17 00:55
For the record, here is the true-minimal repro:

```
use serde::{Deserialize, Serialize};
use serde_unit_struct::{Deserialize_unit_struct, Serialize_unit_struct};

#[derive(Deserialize_unit_struct, Serialize_unit_struct)]
struct Foo;

#[derive(Deserialize, Serialize)]
struct Config {
    foo: Foo,
}

fn main() {
    let original = Config { foo: Foo };
    let serialized = toml::to_string(&original).expect("serialize");
    toml::from_str::<Config>(&serialized).expect("deserialize");
}
```

This is now covered by unit tests to avoid any regressions.

**Comment by cjriches** [comment] 2023-12-16 13:40
I haven't heard back either way regarding the fix, so I will trust the new test suite and release v0.1.3 with this patch.

**Closed as completed by cjriches** 2023-12-16 13:40 UTC
